### ISSUE TITLE
Upload the File

### ISSUE THREAD

**Issue by victoriagjh** [victoriagjh/sentiment_analysis#2]
## Todo
- [x] upload the file to local
- [x] check the file type(txt, csv,json,excel etc..)
- [x] display the file at Second Page

## Related Issues
#1 Basic Web Design

**Comment by victoriagjh** [comment]
- search the file extension of text

**Comment by victoriagjh** [comment]
- check the file name duplicated
if file name is duplicated, file name is changed and can be read another file

**Comment by victoriagjh** [comment]
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class MyModel(models.Model):
    upload = models.FileField(upload_to=user_directory_path)

#(https://docs.djangoproject.com/en/2.2/ref/models/fields/#filefield)

**Comment by victoriagjh** [comment]
Implemented user can upload only "txt"
