### ISSUE TITLE
Natural Language Process Tools

### ISSUE THREAD

**Issue by victoriagjh** [victoriagjh/sentiment_analysis#3]
## Todo
- [x] store the tools that user checked
- [x] develop each tools functions
- [x] show the results each tools that chosen by user at second page

## Related Issues
#1 Basic Web Design

**Comment by hollylululu** [comment]
- 2 tool functions
- Surface metric: vocabulary size
