### ISSUE TITLE
Separate the mode [Expert, Basic]

### ISSUE THREAD

**Issue by victoriagjh** [victoriagjh/sentiment_analysis#6]
## Todo
**Basic Mode**
- tweet level analysis
- [x] show the result whether Positive or Negative (not score)
- [x] confusion matrix
- [x] precise, recall value
- [ ] match function

**Expert Mode**
- sentence level analysis
- [x] word cloud, top frequency word => positive / negative
- [x] hashtag words
- [ ] timeline
- [x] navigation bar

## Related Issues
#3 Natural Language Process Tools

**Comment by victoriagjh** [comment]
@YijiBae Fighting!! 👊🏻

**Comment by victoriagjh** [comment]
- [ ] download the result of each tools
- [ ] change the result according to new sample file
- [ ] make the table about the frequency words

**Comment by victoriagjh** [comment]
ask should we extract the hashtag according to the positive or negative

**Comment by hollylululu** [comment]
As the professor suggested, we will combine the two modes.
